### ISSUE TITLE
Can't load gsw_rho through ctypes on Windows

### ISSUE THREAD

**Issue by geoffstanley** [geoffstanley/neutralocean#15]
In [gswc.py](https://github.com/geoffstanley/neutralocean/blob/main/neutralocean/eos/gswc.py) we access the GSW C library scalar function for in-situ density as follows:
```python
# The following shows how we can access the C library scalar functions that
# are used by GSW-Python, since it is much faster for our jit functions to
# go straight to them rather than going via the Python ufunc wrappers.
dllname = gsw._gsw_ufuncs.__file__
gswlib = ctypes.cdll.LoadLibrary(dllname)
rho_gsw_ctypes = gswlib.gsw_rho  # In-situ density.
```
This works on Ubuntu, but fails on Windows with `AttributeError: function 'gsw_rho' not found` in `gswlib`.

Is there an easy fix for this on Windows?

If not, I may just remove the whole `gswc.py` module, because I have been using a pure Python implementation of GSW specific volume in [gsw.py](https://github.com/geoffstanley/neutralocean/blob/main/neutralocean/eos/gsw.py) since [this commit](https://github.com/geoffstanley/neutralocean/commit/c6a010046deb6bdc30f5dd5654a198d7024d20fd).  This was done for slightly increased speed and for access to third order derivatives; I didn't need the whole GSW toolbox. 

@efiring @ocefpaf

**Comment by efiring** [comment]
https://stackoverflow.com/questions/61263597/ctypes-cant-find-find-dll-function
https://stackoverflow.com/questions/2284610/what-is-declspec-and-when-do-i-need-to-use-it

I suspect this is it: we would need to make a macro that would be empty on non-Windows and would have the "declspec" on Windows, and prefix every C function with it. 
Note that we are using a hack to get around the Microsoft compiler's lack of up-to-date C support: On Windows, we are compiling everything as C++:
https://github.com/TEOS-10/GSW-Python/blob/main/setup.py

**Comment by ocefpaf** [comment]
Linux and MacOS exports the symbols by default but on Windows we need `__declspec(dllexport)`. You can wrap one that function/symbol in your library if ou want with:


```
#ifdef _WIN32
#define DLL_EXPORT __declspec(dllexport)
#else
#define DLL_EXPORT
#endif

DLL_EXPORT double gsw_rho_export(double a, double b, double c) {
  return gsw_rho(a, b, c);
}
```

Thanks @isuruf for the explanation!

**Comment by geoffstanley** [comment]
Thanks @efiring and @ocefpaf . 

It sounds like this is a change you'll consider making to `GSW-Python`. If so, I'll not remove my `gswc.py` module, since in the future it may be useful to go back to that more official source of the equation of state. That said, `neutralocean` currently only uses `gswc.py` in the testing suite -- and in fact I just removed it from there to avoid failing tests on Windows. So, don't feel you have to make this change if it's just for my benefit.

**Comment by ocefpaf** [comment]
@geoffstanley latest gsw should work with cytpes on Windows. Please let us know if that is working for you.
